"""Generate a crontab from config/cron_schedule.yaml.

Wraps each command with `timeout Nm bash -c '<cmd> >> logs/cron/<name>.log 2>&1'`
so jobs that hang get killed and per-job logs land in logs/cron/.

CLI:
  python -m src.deploy.cron_generator                      # to stdout
  python -m src.deploy.cron_generator --output crontab.txt
  python -m src.deploy.cron_generator --validate           # parse only, no output
"""
from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path
from typing import List, Optional

import yaml

log = logging.getLogger(__name__)

DEFAULT_SCHEDULE = Path("config/cron_schedule.yaml")
# Container-absolute path. Cron jobs run from / (no working dir); the
# wrapper cd's to /app before invoking commands so this absolute log path
# is the most explicit choice.
LOG_DIR_ABSOLUTE = "/app/logs/cron"
DEFAULT_USER = "bot"


def load_schedule(path: Path) -> dict:
    if not path.exists():
        raise FileNotFoundError(f"cron schedule not found: {path}")
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def validate_schedule(schedule: dict) -> List[str]:
    """Return list of error messages; empty list if valid."""
    errors: List[str] = []
    if "timezone" not in schedule:
        errors.append("missing required key: timezone")
    jobs = schedule.get("jobs", [])
    if not jobs:
        errors.append("no jobs defined")
    seen_names = set()
    for i, job in enumerate(jobs):
        for k in ("name", "schedule", "command", "timeout_minutes"):
            if k not in job:
                errors.append(f"job[{i}] missing required key: {k}")
        name = job.get("name")
        if name in seen_names:
            errors.append(f"duplicate job name: {name}")
        seen_names.add(name)
        sched = job.get("schedule", "")
        if isinstance(sched, str) and len(sched.split()) != 5:
            errors.append(
                f"job '{name or i}': schedule must have 5 fields, got {sched!r}"
            )
        tmo = job.get("timeout_minutes")
        if not isinstance(tmo, int) or tmo <= 0:
            errors.append(f"job '{name or i}': timeout_minutes must be positive int")
    return errors


def render_crontab(schedule: dict, user: str = DEFAULT_USER) -> str:
    """Build crontab text. Caller writes to stdout or file.

    Each command is wrapped as:
      <schedule> su <user> -c 'cd /app && timeout Nm bash -c "<cmd> >> <log> 2>&1"'

    su is invoked WITHOUT the dash so it inherits env vars (cron exposes
    KEY=value lines from the crontab to job processes; entrypoint.sh
    prepends PUSHOVER_/ALPACA_/SEC_/LOG_DIR for this purpose).
    """
    tz = schedule.get("timezone", "UTC")
    jobs = schedule.get("jobs", [])

    lines: List[str] = []
    lines.append("# strategy_bot crontab -- generated by src/deploy/cron_generator.py")
    lines.append(f"# Timezone: {tz}")
    lines.append(f"# Drop-to-user: {user}")
    lines.append(f"# {len(jobs)} jobs")
    lines.append("")
    lines.append("SHELL=/bin/bash")
    lines.append("PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin")
    lines.append(f"TZ={tz}")
    lines.append("")

    for job in jobs:
        name = job["name"]
        sched = job["schedule"]
        cmd = job["command"]
        timeout_m = int(job["timeout_minutes"])
        desc = job.get("description", "")

        if desc:
            lines.append(f"# {name}: {desc}")
        log_path = f"{LOG_DIR_ABSOLUTE}/{name}.log"
        # Inner command (single-quoted from cron's perspective via the su wrap):
        #   cd /app && timeout Nm bash -c "<user_cmd> >> <log> 2>&1"
        # The double quotes around the bash -c arg let the outer bash (started
        # by su) evaluate $(date +%F) before passing to timeout.
        inner = (
            f"cd /app && timeout {timeout_m}m bash -c "
            f'"{cmd} >> {log_path} 2>&1"'
        )
        wrapped = f"su {user} -c '{_escape_single_quotes(inner)}'"
        lines.append(f"{sched} {wrapped}")
        lines.append("")

    return "\n".join(lines)


def _escape_single_quotes(s: str) -> str:
    """Escape single quotes for inclusion inside a single-quoted shell string."""
    return s.replace("'", "'\\''")


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Generate crontab from YAML")
    parser.add_argument("--schedule", type=Path, default=DEFAULT_SCHEDULE)
    parser.add_argument(
        "--output", type=Path, default=None,
        help="Write to file (default: stdout)",
    )
    parser.add_argument(
        "--validate", action="store_true",
        help="Parse + validate only, no output",
    )
    parser.add_argument(
        "--user", default=DEFAULT_USER,
        help=f"OS user each cron job's su should drop to (default: {DEFAULT_USER})",
    )
    args = parser.parse_args(argv)

    try:
        schedule = load_schedule(args.schedule)
    except FileNotFoundError as e:
        sys.stderr.write(f"ERROR: {e}\n")
        return 1

    errors = validate_schedule(schedule)
    if errors:
        sys.stderr.write("Schedule validation errors:\n")
        for err in errors:
            sys.stderr.write(f"  - {err}\n")
        return 2

    if args.validate:
        sys.stderr.write(
            f"Schedule OK: {len(schedule.get('jobs', []))} jobs, "
            f"tz={schedule.get('timezone')}\n"
        )
        return 0

    text = render_crontab(schedule, user=args.user)
    if args.output is not None:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text, encoding="utf-8")
        sys.stderr.write(f"Wrote {args.output}\n")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
